import { useMemo, useState } from 'react';
import { Download, RefreshCw, Search, X } from 'lucide-react';
import { useGetCrimeTimeline } from '@workspace/api-client-react';
import type { CrimeEvent } from '@workspace/api-client-react';
import { toast } from 'sonner';
import { Card, PageHead, QueryState } from '@/components/shared';

/* ─── Severity + status styling ─────────────────────────────────── */
function severityBadge(s?: string) {
  if (!s) return 'bg-slate-50 text-slate-500 border-slate-200';
  switch (s.toLowerCase()) {
    case 'high': return 'bg-rose-50 text-rose-700 border-rose-200';
    case 'medium': return 'bg-amber-50 text-amber-700 border-amber-200';
    default: return 'bg-slate-50 text-slate-600 border-slate-200';
  }
}

function statusBadge(s: string) {
  const l = s.toLowerCase();
  if (l.includes('open')) return 'bg-amber-50 text-amber-700 border-amber-200';
  if (l.includes('closed') || l.includes('resolved')) return 'bg-emerald-50 text-emerald-700 border-emerald-200';
  return 'bg-sky-50 text-sky-700 border-sky-200';
}

/* ─── Report export ─────────────────────────────────────────────── */
function exportIncidentReport(item: CrimeEvent) {
  const w = window.open('', '_blank');
  if (!w) { toast.error('Pop-up blocked. Please allow pop-ups.'); return; }
  w.document.write(`<!DOCTYPE html><html><head><title>Incident Report — ${item.firNumber}</title>
<style>
  body{font-family:'Segoe UI',sans-serif;color:#1f2d3d;margin:0;padding:0}
  .header{background:#172735;color:#fff;padding:32px 48px}
  .header h1{margin:0 0 4px;font-size:24px} .header p{margin:0;opacity:.6;font-size:13px}
  .badge{display:inline-block;background:#5bbda0;color:#172735;padding:3px 10px;border-radius:20px;font-size:11px;font-weight:700;margin-top:12px}
  .body{padding:40px 48px}
  .grid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:16px;margin:24px 0}
  .kpi{border:1px solid #e2e8f0;border-radius:10px;padding:14px}
  .kpi .label{font-size:10px;text-transform:uppercase;letter-spacing:.1em;color:#94a3b8}
  .kpi .value{font-size:18px;font-weight:700;margin-top:6px}
  .section{margin-top:28px} .section-title{font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.12em;color:#64748b;margin-bottom:10px}
  .summary{background:#f8fafc;border-left:3px solid #5bbda0;padding:14px 18px;border-radius:0 8px 8px 0;font-size:14px;line-height:1.7}
  .footer{margin-top:48px;padding-top:14px;border-top:1px solid #e2e8f0;font-size:11px;color:#94a3b8;display:flex;justify-content:space-between}
  @media print{button{display:none!important}}
</style></head><body>
<div class="header">
  <h1>Incident Report: ${item.firNumber}</h1>
  <p>CrimeLens AI · Karnataka State Police · Field Intelligence</p>
  <span class="badge">${(item.severity ?? 'STANDARD').toUpperCase()} SEVERITY</span>
</div>
<div class="body">
  <div class="grid">
    <div class="kpi"><div class="label">Crime Type</div><div class="value">${item.crimeType}</div></div>
    <div class="kpi"><div class="label">District</div><div class="value">${item.district}</div></div>
    <div class="kpi"><div class="label">Status</div><div class="value">${item.status}</div></div>
  </div>
  <div class="grid" style="grid-template-columns:1fr 1fr">
    <div class="kpi"><div class="label">Police Station</div><div class="value">${item.policeStation}</div></div>
    <div class="kpi"><div class="label">Date Recorded</div><div class="value">${new Date(item.date).toLocaleDateString('en-IN',{day:'2-digit',month:'long',year:'numeric'})}</div></div>
  </div>
  ${item.summary ? `<div class="section"><div class="section-title">Incident Summary</div><div class="summary">${item.summary}</div></div>` : ''}
  <div class="footer"><span>Generated by CrimeLens AI · ${new Date().toLocaleString('en-IN')}</span><span>CONFIDENTIAL — Operational Use Only</span></div>
</div>
<script>window.onload=()=>window.print();</script>
</body></html>`);
  w.document.close();
  toast.success('Report exported');
}

/* ─── Incident card ─────────────────────────────────────────────── */
function IncidentCard({ item, index }: { item: CrimeEvent; index: number }) {
  const [expanded, setExpanded] = useState(false);

  return (
    <div
      className="relative border-b border-slate-100 last:border-0 animate-page-enter"
      style={{ animationDelay: `${Math.min(index * 40, 400)}ms`, animationFillMode: 'both' }}
      data-testid={`timeline-event-${item.id}`}
    >
      {/* Timeline connector */}
      <div className="absolute left-[17px] top-0 bottom-0 w-px bg-slate-100 last:hidden" />

      <div className="relative flex gap-4 py-4 pl-1">
        {/* Dot */}
        <div className={`mt-1 h-4 w-4 shrink-0 rounded-full border-2 ${item.severity?.toLowerCase() === 'high' ? 'border-rose-400 bg-rose-100' : 'border-amber-400 bg-amber-50'}`} />

        <div className="flex-1 min-w-0">
          <div className="flex flex-wrap items-start justify-between gap-2">
            <div>
              <div className="flex flex-wrap items-center gap-2">
                <span className="font-bold text-sm">{item.crimeType}</span>
                {item.severity && (
                  <span className={`rounded-full border px-2 py-0.5 font-mono text-[9px] uppercase font-bold ${severityBadge(item.severity)}`}>
                    {item.severity}
                  </span>
                )}
              </div>
              <div className="mt-1 font-mono text-[10px] text-slate-400">{item.firNumber}</div>
            </div>

            <div className="flex items-center gap-2">
              <span className={`rounded-full border px-2.5 py-1 font-mono text-[9px] uppercase font-bold ${statusBadge(item.status)}`}>
                {item.status}
              </span>
              <button
                onClick={() => exportIncidentReport(item)}
                className="grid h-7 w-7 place-items-center rounded-lg border border-slate-200 bg-white text-slate-400 transition hover:border-[#172735] hover:text-[#172735]"
                title="Export report"
              >
                <Download size={12} />
              </button>
            </div>
          </div>

          <div className="mt-2 flex flex-wrap gap-4 text-xs text-slate-500">
            <span>{item.district} · {item.policeStation}</span>
            <span>{new Date(item.date).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}</span>
          </div>

          {item.summary && (
            <>
              <button onClick={() => setExpanded((v) => !v)} className="mt-2 text-xs font-bold text-emerald-700 hover:underline">
                {expanded ? 'Hide details' : 'View details'}
              </button>
              {expanded && (
                <p className="mt-2 rounded-lg bg-slate-50 px-3 py-2.5 text-xs leading-6 text-slate-600">
                  {item.summary}
                </p>
              )}
            </>
          )}
        </div>
      </div>
    </div>
  );
}

/* ─── Page ──────────────────────────────────────────────────────── */
export default function Incidents() {
  const q = useGetCrimeTimeline();
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState('All');
  const [severity, setSeverity] = useState('All');

  const statuses = useMemo(
    () => ['All', ...new Set((q.data ?? []).map((x) => x.status))],
    [q.data]
  );
  const severities = ['All', 'High', 'Medium', 'Low'];

  const filtered = useMemo(
    () =>
      (q.data ?? []).filter((item) => {
        const text = `${item.firNumber} ${item.crimeType} ${item.district} ${item.summary ?? ''}`.toLowerCase();
        const matchSearch = !search || text.includes(search.toLowerCase());
        const matchStatus = filter === 'All' || item.status === filter;
        const matchSev = severity === 'All' || (item.severity ?? '').toLowerCase() === severity.toLowerCase();
        return matchSearch && matchStatus && matchSev;
      }),
    [q.data, search, filter, severity]
  );

  const handleRefresh = () => {
    void q.refetch();
    toast.success('Incident records synced');
  };

  return (
    <>
      <PageHead
        eyebrow="Field records"
        title="Incident timeline"
        detail="A chronological evidence register for current and historical crime events across Karnataka."
        action={
          <button
            onClick={handleRefresh}
            className="inline-flex items-center gap-2 rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-xs font-bold"
            data-testid="button-refresh-incidents"
          >
            <RefreshCw size={14} /> Sync records
          </button>
        }
      />

      <Card>
        {/* Search + filters */}
        <div className="mb-5 flex flex-col gap-3">
          <div className="relative">
            <Search size={16} className="absolute left-3 top-3 text-slate-400" />
            <input
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="Search by FIR number, crime type, district or description…"
              className="h-11 w-full rounded-lg border border-slate-300 bg-slate-50 pl-9 pr-10 text-sm outline-none focus:border-emerald-500 focus:bg-white"
              data-testid="input-search-incidents"
            />
            {search && (
              <button onClick={() => setSearch('')} className="absolute right-3 top-3 text-slate-400 hover:text-slate-700">
                <X size={15} />
              </button>
            )}
          </div>

          <div className="flex flex-wrap gap-2">
            {/* Status filters */}
            <div className="flex gap-1.5 overflow-auto">
              {statuses.map((item) => (
                <button
                  key={item}
                  onClick={() => setFilter(item)}
                  className={`whitespace-nowrap rounded-lg border px-3 py-1.5 text-xs font-bold transition ${filter === item ? 'border-[#172735] bg-[#172735] text-white' : 'border-slate-200 bg-white text-slate-500 hover:border-slate-300'}`}
                  data-testid={`button-filter-${item}`}
                >
                  {item}
                </button>
              ))}
            </div>

            <div className="ml-auto flex gap-1.5">
              {severities.map((s) => (
                <button
                  key={s}
                  onClick={() => setSeverity(s)}
                  className={`rounded-lg border px-3 py-1.5 text-xs font-bold transition ${severity === s
                    ? s === 'High' ? 'border-rose-600 bg-rose-600 text-white'
                      : s === 'Medium' ? 'border-amber-500 bg-amber-500 text-white'
                        : 'border-[#172735] bg-[#172735] text-white'
                    : 'border-slate-200 bg-white text-slate-500 hover:border-slate-300'}`}
                >
                  {s}
                </button>
              ))}
            </div>
          </div>

          {(search || filter !== 'All' || severity !== 'All') && (
            <div className="flex items-center gap-2 text-xs text-slate-500">
              <span>{filtered.length} of {q.data?.length ?? 0} records</span>
              <button onClick={() => { setSearch(''); setFilter('All'); setSeverity('All'); }} className="font-bold text-emerald-700 hover:underline">
                Clear filters
              </button>
            </div>
          )}
        </div>

        {/* Timeline */}
        <QueryState
          loading={q.isLoading}
          error={q.error}
          empty={!filtered.length}
          onRetry={() => q.refetch()}
          emptyMessage="No incidents match the current filters."
        >
          <div className="pl-4">
            {filtered.map((item, i) => <IncidentCard item={item} index={i} key={item.id} />)}
          </div>
        </QueryState>
      </Card>
    </>
  );
}
