import { useEffect, useMemo, useRef, useState } from 'react';
import { Search, ZoomIn, ZoomOut, Maximize2, Download } from 'lucide-react';
import { useGetRepeatOffenderRanking, useGetOffenderNetwork, useGetOffender } from '@workspace/api-client-react';
import type { NetworkNode, NetworkEdge } from '@workspace/api-client-react';
import { toast } from 'sonner';
import { Card, PageHead, QueryState } from '@/components/shared';

/* ─── Report export ─────────────────────────────────────────────── */
function exportOffenderReport(
  profile: { name: string; age: number; gender: string; riskScore: number; criminalHistory: number; modusOperandi: string; crimes?: Array<{ firNumber: string; crimeType: string; district: string; date: string }> },
) {
  const w = window.open('', '_blank');
  if (!w) { toast.error('Pop-up blocked. Please allow pop-ups.'); return; }
  const crimes = (profile.crimes ?? [])
    .map((c) => `<tr><td>${c.firNumber}</td><td>${c.crimeType}</td><td>${c.district}</td><td>${new Date(c.date).toLocaleDateString('en-IN')}</td></tr>`)
    .join('');
  w.document.write(`<!DOCTYPE html><html><head><title>Investigation Report — ${profile.name}</title>
<style>
  body { font-family: 'Segoe UI', sans-serif; color: #1f2d3d; margin: 0; padding: 0; }
  .header { background: #172735; color: white; padding: 32px 48px; }
  .header h1 { margin: 0 0 4px; font-size: 28px; } .header p { margin: 0; opacity: .6; font-size: 13px; }
  .badge { display: inline-block; background: #5bbda0; color: #172735; padding: 3px 10px; border-radius: 20px; font-size: 11px; font-weight: 700; margin-top: 12px; }
  .body { padding: 40px 48px; }
  .grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 20px; margin: 24px 0; }
  .kpi { border: 1px solid #e2e8f0; border-radius: 10px; padding: 16px; }
  .kpi .label { font-size: 10px; text-transform: uppercase; letter-spacing: .1em; color: #94a3b8; }
  .kpi .value { font-size: 24px; font-weight: 700; margin-top: 6px; }
  table { width: 100%; border-collapse: collapse; margin-top: 16px; font-size: 13px; }
  th { text-align: left; font-size: 10px; text-transform: uppercase; letter-spacing: .08em; color: #94a3b8; padding: 8px 12px; border-bottom: 2px solid #e2e8f0; }
  td { padding: 10px 12px; border-bottom: 1px solid #f1f5f9; }
  .section-title { font-size: 13px; font-weight: 700; text-transform: uppercase; letter-spacing: .1em; color: #64748b; margin: 32px 0 8px; }
  .modus { background: #f8fafc; border-left: 3px solid #5bbda0; padding: 14px 18px; border-radius: 0 8px 8px 0; font-size: 14px; line-height: 1.7; }
  .footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; display: flex; justify-content: space-between; }
  @media print { button { display: none !important; } }
</style></head><body>
<div class="header">
  <h1>Investigation Profile: ${profile.name}</h1>
  <p>CrimeLens AI · Karnataka State Police · Intelligence Division</p>
  <span class="badge">RISK SCORE ${profile.riskScore}</span>
</div>
<div class="body">
  <div class="grid">
    <div class="kpi"><div class="label">Age / Gender</div><div class="value">${profile.age} · ${profile.gender}</div></div>
    <div class="kpi"><div class="label">Criminal Records</div><div class="value">${profile.criminalHistory}</div></div>
    <div class="kpi"><div class="label">Risk Rating</div><div class="value" style="color:${profile.riskScore > 70 ? '#f43f5e' : '#f59e0b'}">${profile.riskScore > 70 ? 'HIGH' : 'MEDIUM'}</div></div>
  </div>
  <div class="section-title">Modus Operandi</div>
  <div class="modus">${profile.modusOperandi || 'No description on file.'}</div>
  ${crimes ? `<div class="section-title">Linked Incidents</div><table><thead><tr><th>FIR</th><th>Crime Type</th><th>District</th><th>Date</th></tr></thead><tbody>${crimes}</tbody></table>` : ''}
  <div class="footer"><span>Generated by CrimeLens AI · ${new Date().toLocaleString('en-IN')}</span><span>CONFIDENTIAL — Operational Use Only</span></div>
</div>
<script>window.onload = () => window.print();</script>
</body></html>`);
  w.document.close();
  toast.success('Report exported');
}

/* ─── Node type colours ─────────────────────────────────────────── */
const NODE_COLORS: Record<string, { fill: string; stroke: string; text: string }> = {
  offender:  { fill: '#5bbda0', stroke: '#3a9e85', text: '#172735' },
  associate: { fill: '#172735', stroke: '#0f1c24', text: '#ffffff' },
  location:  { fill: '#f59e0b', stroke: '#d97706', text: '#172735' },
  incident:  { fill: '#f43f5e', stroke: '#e11d48', text: '#ffffff' },
  default:   { fill: '#dce9ea', stroke: '#94a3b8', text: '#1f2d3d' },
};

function nodeColor(type: string) {
  return NODE_COLORS[type.toLowerCase()] ?? NODE_COLORS.default;
}

/* ─── SVG Network ───────────────────────────────────────────────── */
function NetworkSvg({
  nodes, edges, centerId,
}: { nodes: NetworkNode[]; edges: NetworkEdge[]; centerId: string }) {
  const [selected, setSelected] = useState<string | null>(null);
  const [pan, setPan] = useState({ x: 0, y: 0 });
  const [zoom, setZoom] = useState(1);
  const dragging = useRef(false);
  const lastMouse = useRef({ x: 0, y: 0 });
  const svgRef = useRef<SVGSVGElement>(null);
  const W = 780, H = 480, CX = W / 2, CY = H / 2, R = 185;

  /* Radial layout */
  const positions = useMemo<Record<string, { x: number; y: number }>>(() => {
    const pos: Record<string, { x: number; y: number }> = {};
    pos[centerId] = { x: CX, y: CY };
    const others = nodes.filter((n) => n.id !== centerId);
    others.forEach((n, i) => {
      const angle = (i / Math.max(others.length, 1)) * 2 * Math.PI - Math.PI / 2;
      pos[n.id] = { x: CX + Math.cos(angle) * R, y: CY + Math.sin(angle) * R };
    });
    return pos;
  }, [nodes, centerId]);

  /* Highlighted node set */
  const highlighted = useMemo(() => {
    if (!selected) return new Set<string>();
    const set = new Set([selected]);
    edges.forEach((e) => {
      if (e.source === selected) set.add(e.target);
      if (e.target === selected) set.add(e.source);
    });
    return set;
  }, [selected, edges]);

  const connectedEdges = new Set(
    selected ? edges.filter((e) => e.source === selected || e.target === selected).map((e) => e.id) : []
  );

  /* Wheel zoom */
  const handleWheel = (e: React.WheelEvent) => {
    e.preventDefault();
    const delta = e.deltaY > 0 ? 0.88 : 1.14;
    setZoom((z) => Math.min(3, Math.max(0.3, z * delta)));
  };

  /* Pan */
  const handleMouseDown = (e: React.MouseEvent) => {
    if (e.button !== 0) return;
    dragging.current = true;
    lastMouse.current = { x: e.clientX, y: e.clientY };
  };
  const handleMouseMove = (e: React.MouseEvent) => {
    if (!dragging.current) return;
    setPan((p) => ({ x: p.x + e.clientX - lastMouse.current.x, y: p.y + e.clientY - lastMouse.current.y }));
    lastMouse.current = { x: e.clientX, y: e.clientY };
  };
  const handleMouseUp = () => { dragging.current = false; };

  const fitToScreen = () => { setZoom(1); setPan({ x: 0, y: 0 }); setSelected(null); };

  return (
    <div className="relative overflow-hidden rounded-xl bg-[#0d1b26]" style={{ height: 460 }}>
      {/* Controls */}
      <div className="absolute right-3 top-3 z-10 flex flex-col gap-1.5">
        {[
          { icon: <ZoomIn size={15} />, fn: () => setZoom((z) => Math.min(3, z * 1.2)) },
          { icon: <ZoomOut size={15} />, fn: () => setZoom((z) => Math.max(0.3, z * 0.8)) },
          { icon: <Maximize2 size={15} />, fn: fitToScreen },
        ].map(({ icon, fn }, i) => (
          <button key={i} onClick={fn} className="grid h-8 w-8 place-items-center rounded-lg bg-white/10 text-white/70 transition hover:bg-white/20 hover:text-white">
            {icon}
          </button>
        ))}
      </div>

      {/* Legend */}
      <div className="absolute bottom-3 left-3 z-10 flex flex-wrap gap-2">
        {Object.entries(NODE_COLORS).filter(([k]) => k !== 'default').map(([type, c]) => (
          <span key={type} className="flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[10px] font-bold backdrop-blur" style={{ background: c.fill + '22', color: c.fill, border: `1px solid ${c.fill}44` }}>
            <span className="h-2 w-2 rounded-full" style={{ background: c.fill }} />{type}
          </span>
        ))}
      </div>

      {/* Node count */}
      <div className="absolute left-3 top-3 z-10 font-mono text-[10px] text-white/40">
        {nodes.length} nodes · {edges.length} links
      </div>

      <svg
        ref={svgRef}
        width="100%" height="100%"
        viewBox={`0 0 ${W} ${H}`}
        onWheel={handleWheel}
        onMouseDown={handleMouseDown}
        onMouseMove={handleMouseMove}
        onMouseUp={handleMouseUp}
        onMouseLeave={handleMouseUp}
        style={{ cursor: dragging.current ? 'grabbing' : 'grab' }}
      >
        <defs>
          <style>{`@keyframes dashMove{to{stroke-dashoffset:-20}} .edge-anim{animation:dashMove 1.2s linear infinite}`}</style>
          {/* Grid pattern */}
          <pattern id="grid" width="36" height="36" patternUnits="userSpaceOnUse">
            <path d="M 36 0 L 0 0 0 36" fill="none" stroke="#5bbda0" strokeWidth="0.4" strokeOpacity="0.15" />
          </pattern>
        </defs>
        <rect width="100%" height="100%" fill="url(#grid)" />
        <g transform={`translate(${pan.x},${pan.y}) scale(${zoom})`} style={{ transformOrigin: `${CX}px ${CY}px` }}>
          {/* Edges */}
          {edges.map((edge) => {
            const s = positions[edge.source];
            const t = positions[edge.target];
            if (!s || !t) return null;
            const isActive = connectedEdges.has(edge.id);
            const isDimmed = selected && !isActive;
            return (
              <g key={edge.id}>
                <line
                  x1={s.x} y1={s.y} x2={t.x} y2={t.y}
                  stroke={isActive ? '#5bbda0' : '#334155'}
                  strokeWidth={isActive ? 2 : 1}
                  strokeDasharray={isActive ? '6 4' : '3 5'}
                  strokeOpacity={isDimmed ? 0.15 : isActive ? 0.9 : 0.45}
                  className={isActive ? 'edge-anim' : ''}
                />
                {/* Confidence label on active edges */}
                {isActive && (
                  <text
                    x={(s.x + t.x) / 2} y={(s.y + t.y) / 2 - 6}
                    textAnchor="middle" fill="#5bbda0" fontSize="9"
                    fontFamily="DM Mono" opacity="0.85"
                  >
                    {Math.round(edge.confidenceScore * 100)}%
                  </text>
                )}
              </g>
            );
          })}

          {/* Nodes */}
          {nodes.map((node) => {
            const p = positions[node.id];
            if (!p) return null;
            const isCenter = node.id === centerId;
            const isSelected = selected === node.id;
            const isDimmed = selected && !highlighted.has(node.id);
            const c = nodeColor(node.type);
            const r = isCenter ? 34 : 22;
            return (
              <g
                key={node.id}
                transform={`translate(${p.x},${p.y})`}
                style={{ cursor: 'pointer', opacity: isDimmed ? 0.25 : 1, transition: 'opacity 0.2s' }}
                onClick={(e) => { e.stopPropagation(); setSelected(selected === node.id ? null : node.id); }}
              >
                {/* Glow ring for selected */}
                {isSelected && <circle r={r + 10} fill={c.fill} opacity={0.18} />}
                {isCenter && <circle r={r + 14} fill={c.fill} opacity={0.1} />}
                <circle r={r} fill={c.fill} stroke={c.stroke} strokeWidth={isSelected ? 2.5 : 1.5} />
                <text y={4} textAnchor="middle" fill={c.text} fontSize={isCenter ? 10 : 9} fontFamily="DM Mono" fontWeight="700">
                  {node.label.slice(0, 8)}
                </text>
                {/* Type badge */}
                <text y={r + 14} textAnchor="middle" fill="#94a3b8" fontSize="8" fontFamily="DM Mono">
                  {node.type}
                </text>
              </g>
            );
          })}
        </g>
      </svg>
    </div>
  );
}

/* ─── Page ──────────────────────────────────────────────────────── */
export default function NetworkPage() {
  const ranking = useGetRepeatOffenderRanking();
  const [selectedId, setSelectedId] = useState<number>(1);
  const [nodeSearch, setNodeSearch] = useState('');
  const network = useGetOffenderNetwork(selectedId);
  const profile = useGetOffender(selectedId);

  const filteredRanking = useMemo(
    () => (ranking.data ?? []).filter((p) => p.name.toLowerCase().includes(nodeSearch.toLowerCase())),
    [ranking.data, nodeSearch]
  );

  return (
    <>
      <PageHead
        eyebrow="Relationship intelligence"
        title="Network explorer"
        detail="Follow the links between people, places and incidents. Select a subject to inspect their connected record."
      />

      <div className="grid gap-5 xl:grid-cols-[.75fr_1.5fr]">
        {/* Subjects panel */}
        <Card title="Subjects of interest" meta="Ranked by repeat-offender risk">
          <div className="relative mb-3">
            <Search size={14} className="absolute left-3 top-3 text-slate-400" />
            <input
              value={nodeSearch}
              onChange={(e) => setNodeSearch(e.target.value)}
              placeholder="Search subjects…"
              className="h-10 w-full rounded-lg border border-slate-200 bg-slate-50 pl-9 pr-3 text-sm outline-none focus:border-emerald-500 focus:bg-white"
            />
          </div>
          <div className="max-h-[460px] overflow-y-auto space-y-1 pr-1">
            <QueryState loading={ranking.isLoading} error={ranking.error} empty={!filteredRanking.length}>
              {filteredRanking.map((person) => (
                <button
                  onClick={() => { setSelectedId(person.id); setNodeSearch(''); }}
                  className={`flex w-full items-center gap-3 rounded-lg p-3 text-left transition ${selectedId === person.id ? 'bg-[#172735] text-white' : 'hover:bg-slate-50'}`}
                  key={person.id}
                  data-testid={`button-select-offender-${person.id}`}
                >
                  <div className={`grid h-8 w-8 shrink-0 place-items-center rounded-full font-display text-xs font-bold ${selectedId === person.id ? 'bg-emerald-400 text-[#172735]' : 'bg-slate-200 text-slate-600'}`}>
                    {person.name.slice(0, 2).toUpperCase()}
                  </div>
                  <div className="min-w-0 flex-1">
                    <div className="truncate text-xs font-bold">{person.name}</div>
                    <div className={`text-[10px] ${selectedId === person.id ? 'text-slate-400' : 'text-slate-500'}`}>{person.incidents} incidents · {person.status}</div>
                  </div>
                  <span className={`shrink-0 font-mono text-xs font-bold ${person.riskScore > 70 ? 'text-rose-400' : 'text-amber-400'}`}>{person.riskScore}</span>
                </button>
              ))}
            </QueryState>
          </div>
        </Card>

        {/* Graph + profile */}
        <div className="flex flex-col gap-5">
          <QueryState loading={network.isLoading} error={network.error}>
            {network.data && (
              <NetworkSvg
                nodes={network.data.nodes}
                edges={network.data.edges}
                centerId={String(selectedId)}
              />
            )}
          </QueryState>

          <Card title="Subject profile" meta={`Subject ID ${selectedId}`} action={
            profile.data && (
              <button
                onClick={() => exportOffenderReport(profile.data!)}
                className="inline-flex items-center gap-1.5 rounded-lg bg-[#172735] px-3 py-1.5 text-xs font-bold text-white transition hover:bg-[#203c4c]"
              >
                <Download size={13} /> Generate Report
              </button>
            )
          }>
            <QueryState loading={profile.isLoading} error={profile.error}>
              {profile.data && (
                <div className="grid gap-5 md:grid-cols-2">
                  <div>
                    <div className="flex items-center gap-3">
                      <div className="grid h-12 w-12 place-items-center rounded-full bg-[#dce9ea] font-display text-lg font-bold text-[#31566a]">
                        {profile.data.name.slice(0, 2).toUpperCase()}
                      </div>
                      <div>
                        <h3 className="font-display text-xl font-bold">{profile.data.name}</h3>
                        <span className={`font-mono text-[10px] uppercase tracking-wider ${profile.data.riskScore > 70 ? 'text-rose-600' : 'text-amber-600'}`}>
                          Risk score {profile.data.riskScore} · {profile.data.riskScore > 70 ? 'HIGH' : 'MEDIUM'}
                        </span>
                      </div>
                    </div>
                    <dl className="mt-5 grid grid-cols-2 gap-3 text-xs">
                      <div className="rounded-lg bg-slate-50 p-3"><dt className="text-slate-400">Age / Gender</dt><dd className="mt-1 font-bold">{profile.data.age} · {profile.data.gender}</dd></div>
                      <div className="rounded-lg bg-slate-50 p-3"><dt className="text-slate-400">Prior history</dt><dd className="mt-1 font-bold">{profile.data.criminalHistory} records</dd></div>
                    </dl>
                  </div>
                  <div>
                    <div className="font-mono text-[9px] uppercase tracking-wider text-slate-400 mb-2">Modus operandi</div>
                    <p className="text-sm leading-6 text-slate-600 bg-slate-50 rounded-lg p-3">{profile.data.modusOperandi || 'No description on file.'}</p>
                    {profile.data.crimes?.length ? (
                      <div className="mt-4">
                        <div className="font-mono text-[9px] uppercase tracking-wider text-slate-400 mb-2">Linked incidents ({profile.data.crimes.length})</div>
                        <div className="max-h-28 overflow-y-auto space-y-1">
                          {profile.data.crimes.map((c) => (
                            <div key={c.id} className="flex items-center gap-2 rounded bg-slate-50 px-3 py-2 text-xs">
                              <span className="font-mono text-[10px] text-slate-400">{c.firNumber}</span>
                              <span className="font-semibold">{c.crimeType}</span>
                              <span className="ml-auto text-slate-400">{c.district}</span>
                            </div>
                          ))}
                        </div>
                      </div>
                    ) : null}
                  </div>
                </div>
              )}
            </QueryState>
          </Card>
        </div>
      </div>
    </>
  );
}
